# Generated by Django 4.1.4 on 2022-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_id_item_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
            ],
        ),
    ]
